---
- name: 'Primer playbook'
  hosts: all
  remote_user: frankerFcp2
  become: true
  vars_files:
    - vars/00_vars.yaml  
  tasks:
    # declara la zona horaria con el valor de la variable zone
    - name: 'Tarea 1'
      timezone:
        name: "{{ zone }}"
    # instala el paquete definido en rpms
    - name: 'Tarea 2'
      yum: 
        name: "{{ rpms }}"
        state: latest
    # Cambia el mensaje de bienvenida      
    - name: 'Copiar plantilla de motd'
      template:
        src: templates/motd.j2
        dest: /etc/motd        