---
- name: 'generar imagen contenedor servicio web etiquetar y subir'
  hosts: localhost  
  vars_files:
    - vars/varscontainers.yaml   
  tasks:
    
    - name: 'generar imagen contenedor a partir del containerfile'
      containers.podman.podman_image:
        name: casopractico2
        path: files

    - name: 'etiquetar la imagen'
      containers.podman.podman_tag:
        image: localhost/casopractico2
        target_names:
          - "{{podmanweb.image}}"

    - name: 'generar imagen wordpress'
      containers.podman.podman_image:
        name: docker.io/wordpress:latest
    
    - name: 'etiquetar imagen wordpress'
      containers.podman.podman_tag:
        image: docker.io/wordpress:latest
        target_names:
          - "{{podmanwp.image}}"

    - name: 'generar imagen mysql'
      containers.podman.podman_image:
        name: docker.io/mysql:latest
    
    - name: 'etiquetar imagen mysql'
      containers.podman.podman_tag:
        image: docker.io/mysql:latest
        target_names:
          - "{{podmanmysql.image}}"

    # Login para subir imagen al repositorio
    - name: 'Login to podman'
      containers.podman.podman_login:
        username: "{{ registryuser }}"
        password: "{{ resgistrypassword }}"
        registry: "{{ registry }}"          


    - name: 'push de la imagen tageada'
      containers.podman.podman_image:
        name: webserver
        tag: casopractico2
        push: true
        push_args:
          dest: "{{ registry }}"

    - name: 'push imagen wordpress'
      containers.podman.podman_image:
        name: wordpress
        tag: casopractico2
        push: true
        push_args:
          dest: "{{ registry }}"

    - name: 'push imagen mysql'          
      containers.podman.podman_image:
        name: mysql
        tag: casopractico2
        push: true
        push_args:
          dest: "{{ registry }}"

    - name: 'eliminacion de las imágenes locales'
      containers.podman.podman_image:
        name: "{{podmanweb.image}}"          
        state: absent

    - name: 'eliminacion de las imágenes locales'
      containers.podman.podman_image:
        name: localhost/casopractico2
        state: absent

        